FROM node:20

WORKDIR /app
COPY package*.json ./

# Instalamos las dependencias de la aplicacion
RUN npm install

# Copiamos el resto de elementos de la aplicacion
COPY ./web ./web

# Iniciamos la aplicacion (puerto 3000)
CMD npm start